### ISSUE TITLE
One XHR object for each blob.

### ISSUE THREAD

**Issue by thecolorblue** [ienzam/s3-multipart-upload-browser#1]
I want to start with saying this is the best example of uploading to S3 I have seen yet. I have been playing around with doing this exact thing and have gotten frustrated because there is no good documentation. 

Now for my question, it looks like this example creates another XMLHTTPRequest for each blob (in the js). Is that needed? It seems excessive.

**Comment by ienzam** [comment]
My initial target is to write a parallel uploading system (after all it is chunk upload, we need to take the benefit :p ).
But I am in a hurry to develop a system (this is part of the system), so for now going with serial.
If you want to contribute (change to one XMLHTTPRequest and / or make parallel) I will be very very happy.
BTW, unit testing is coming soon for the php part :D
